CREATE TABLE [dbo].[Client]
(
	[IdClient] INT NOT NULL IDENTITY,
	[Email] NVARCHAR(323) NOT NULL,
	[Prenom] NVARCHAR(50) NOT NULL,
	[Nom] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(600) NOT NULL,
	[Salt] NVARCHAR(250) NOT NULL,

	CONSTRAINT PK_Client PRIMARY KEY ([IdClient]),
	CONSTRAINT UK_User_Email UNIQUE ([Email]),
	CONSTRAINT CK_User_Email CHECK ([Email] LIKE '___%@___%.__%')
)
