CREATE TABLE [dbo].[Cours]
(
	[IdCours] INT NOT NULL IDENTITY,
	[NomCours] NVARCHAR(50) NOT NULL,
	[MaxParticipants] INT NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[Image] NVARCHAR(512) NOT NULL,
	[IdProf] INT NOT NULL,

	CONSTRAINT PK_Cours PRIMARY KEY ([IdCours]),
	CONSTRAINT FK_Cours_Prof FOREIGN KEY ([IdProf]) REFERENCES [Prof],
	CONSTRAINT UK_Nom_Cours UNIQUE ([NomCours])

)
