CREATE TABLE [dbo].[Prof]
(
	[IdProf] INT NOT NULL IDENTITY,
	[Prenom] NVARCHAR(64) NOT NULL,
	[InfoProf] NVARCHAR(MAX) NOT NULL,
	[Photo] NVARCHAR(250) NOT NULL, 

    CONSTRAINT PK_Prof PRIMARY KEY ([IdProf])
)
