CREATE TABLE [dbo].[Prof]
(
	[IdProf] INT NOT NULL IDENTITY,
	[Prenom] VARCHAR(64) NOT NULL,
	[InfoProf] VARCHAR(MAX) NOT NULL,
	[Photo] VARCHAR(250) NOT NULL, 

    CONSTRAINT PK_Prof PRIMARY KEY ([IdProf])
)
